-- ============================================================
-- FuelOS Migration: 001_enable_rls.sql
-- Enable Row Level Security on all tables
-- Run this on each dealer's Supabase project
-- ============================================================

BEGIN;

-- Infrastructure
ALTER TABLE "FuelStation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "StationSettings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ReportSettings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "WebhookConfig" ENABLE ROW LEVEL SECURITY;

-- User & Access
ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PayrollPermission" ENABLE ROW LEVEL SECURITY;

-- Assets
ALTER TABLE "Pump" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Tank" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Nozzle" ENABLE ROW LEVEL SECURITY;

-- Operations
ALTER TABLE "Shift" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "NozzleEntry" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PaymentRecord" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "FuelRate" ENABLE ROW LEVEL SECURITY;

-- Credit
ALTER TABLE "CreditCustomer" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CreditTransaction" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CreditPayment" ENABLE ROW LEVEL SECURITY;

-- Inventory
ALTER TABLE "FuelOrder" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "InventoryCheque" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "StockTransaction" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DipReading" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TankInitialStock" ENABLE ROW LEVEL SECURITY;

-- HR
ALTER TABLE "SalaryConfig" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "StaffAdvance" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SalaryPayout" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "StaffArchiveRequest" ENABLE ROW LEVEL SECURITY;

-- Logs
ALTER TABLE "AuditLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Notification" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Receipt" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DailyExpense" ENABLE ROW LEVEL SECURITY;

-- Reports
ALTER TABLE "GeneratedReport" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "GeneratedReportArtifact" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "MessageQueue" ENABLE ROW LEVEL SECURITY;

COMMIT;
